print("salom git! men python organayapman!") 
print("Yangi funksiya!") 
print("GitHubdan kelgan kod!")
print("GitHubdan yangi qator")
print("Masterda boshqacha ozgarish") print("Stash testi") 
print("Cherry pick testi") 
